apiVersion: V1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
       app: nodeapp
  templete:
    metadata: 
       labels:
         app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image:gatreya/nodeapp
          ports:
            - containersPort: 8080
